export const categoriasDisponibles = [
  // Originales
  "Electricista",
  "Plomero",
  "Pintor",
  "Carpintero",
  "Cerrajero",
  "Mecánico",
  "Jardinero",
  "Mudanzas",
  "Profesor particular",
  "Disenador gráfico",
  "Programador",
  "Contador",
  "Fotógrafo",
  "Veterinario",
  "Asistente virtual",
  "Estilista",
  "Tatuador",
  "Marketing",
  "Traductor",
  "Cuidado de niños",
  "Cuidado de ancianos",
  "Entrenador personal",
  "Técnico de PC",
  "Desarrollador web",
  "Servicio de limpieza",
  "Chofer privado",
  "Decorador de interiores",
  "Chef personal",
  "Organizador de eventos",
  "Masajista",
  "Fletes",
  "Albañil",
  "Reparaciones en el hogar",
  "Community Manager",
  "Editor de video",
  "Paseador de perros",
  "Atención al cliente",
  "Reparación de celulares",
  "Profesor de música",

  // Nuevas
  "Soldador",
  "Gasista",
  "Herrero",
  "Asistente contable",
  "Psicólogo",
  "Kinesiólogo",
  "Nutricionista",
  "Enfermero",
  "Disenador UX/UI",
  "Ilustrador",
  "Guionista",
  "Camarógrafo",
  "Gestor de redes",
  "Tester QA",
  "Coach de vida",
  "Terapista ocupacional",
  "Maquillador profesional",
  "Manicurista",
  "Técnico en refrigeración",
  "Montador de muebles",
  "Bartender",
  "Mozos para eventos",
  "Dj para eventos",
  "Instalador de cámaras",
  "Animador infantil",
  "Profesor de yoga",
  "Instructor de manejo",
  "Lavado de autos",
  "guarderia de mascotas",
  "Personal de seguridad",
  "Coach financiero",
  "Redactor de contenidos",
  "Consultor de negocios",
  "Instalador de paneles solares",
  "Reparador de electrodomésticos",
  "Tapicero",
  "Modista",
  "Sastre",
  "Montador de estructuras",
  "Disenador industrial",
  "Fotógrafo de producto",
  "Traductor jurado",
  "Desarrollador de apps",
  "Gestor de ecommerce",
  "Abogado",
  "Artesano",
  "Consultor ambiental",
  "Encargado de depósito",
  "Camarero",
  "Panadero",
  "Pastelero",
  "Delivery",
  "Personal de limpieza de oficinas",

  "Ingeniero",
  "Médico",
  "Arquitecto",
  "Odontólogo",
  "Salón de fiestas infantiles",
  "Salón de fiestas",
  "Decoraciones para eventos",
  "Instalador de aire acondicionado",
  "Gestor de trámites",
  "Peluquería de mascotas",
  "Cocinero",
  "Ayudante de cocina",
  "Empleada doméstica",
  "Limpieza comercial",
];

export const iconosCategoria = {
  // EXISTENTES
  Electricista: require("../../assets/icons/electricista.png"),
  Plomero: require("../../assets/icons/plomero.png"),
  Pintor: require("../../assets/icons/pintor.png"),
  Carpintero: require("../../assets/icons/carpintero.png"),
  Cerrajero: require("../../assets/icons/cerrajero.png"),
  Mecánico: require("../../assets/icons/mecanico.png"),
  Jardinero: require("../../assets/icons/jardinero.png"),
  Mudanzas: require("../../assets/icons/mudanzas.png"),
  "Profesor particular": require("../../assets/icons/profesor_particular.png"),
  "Diseñador gráfico": require("../../assets/icons/disenador_grafico.png"),
  Programador: require("../../assets/icons/programador.png"),
  Contador: require("../../assets/icons/contador.png"),
  Fotógrafo: require("../../assets/icons/fotografo.png"),
  Veterinario: require("../../assets/icons/veterinario.png"),
  "Asistente virtual": require("../../assets/icons/asistente_virtual.png"),
  Estilista: require("../../assets/icons/estilista.png"),
  Tatuador: require("../../assets/icons/tatuador.png"),
  Marketing: require("../../assets/icons/marketing.png"),
  Traductor: require("../../assets/icons/traductor.png"),
  "Cuidado de niños": require("../../assets/icons/cuidado_ninos.png"),
  "Cuidado de adultos mayores": require("../../assets/icons/cuidado_adultos_mayores.png"),
  "Entrenador personal": require("../../assets/icons/entrenador_personal.png"),
  "Técnico de PC": require("../../assets/icons/tecnico_pc.png"),
  "Desarrollador web": require("../../assets/icons/desarrollador_web.png"),
  "Servicio de limpieza": require("../../assets/icons/servicio_limpieza.png"),
  "Chofer privado": require("../../assets/icons/chofer_privado.png"),
  "Decorador de interiores": require("../../assets/icons/decorador_interiores.png"),
  "Chef personal": require("../../assets/icons/chef_personal.png"),
  "Organizador de eventos": require("../../assets/icons/organizador_eventos.png"),
  Masajista: require("../../assets/icons/masajista.png"),
  Fletes: require("../../assets/icons/fletes.png"),
  Albañil: require("../../assets/icons/albanil.png"),
  "Reparaciones en el hogar": require("../../assets/icons/reparaciones_hogar.png"),
  "Community Manager": require("../../assets/icons/community_manager.png"),
  "Editor de video": require("../../assets/icons/editor_video.png"),
  "Paseador de perros": require("../../assets/icons/paseador_perros.png"),
  "Atención al cliente": require("../../assets/icons/atencion_cliente.png"),
  "Reparación de celulares": require("../../assets/icons/reparacion_celulares.png"),
  "Profesor de música": require("../../assets/icons/profesor_musica.png"),

  Soldador: require("../../assets/icons/soldador.png"),
  Gasista: require("../../assets/icons/gasista.png"),
  Herrero: require("../../assets/icons/herrero.png"),
  "Asistente contable": require("../../assets/icons/asistente_contable.png"),
  Psicólogo: require("../../assets/icons/psicologo.png"),
  Kinesiólogo: require("../../assets/icons/kinesiologo.png"),
  Nutricionista: require("../../assets/icons/nutricionista.png"),
  Enfermero: require("../../assets/icons/enfermera.png"),
  Ilustrador: require("../../assets/icons/ilustrador.png"),
  Guionista: require("../../assets/icons/guionista.png"),
  Camarógrafo: require("../../assets/icons/camarografo.png"),
  "Gestor de redes": require("../../assets/icons/gestor_redes_sociales.png"),
  "Tester QA": require("../../assets/icons/tester_QA.png"),
  "Coach de vida": require("../../assets/icons/coach_vida.png"),
  "Terapista ocupacional": require("../../assets/icons/terapista_ocupacional.png"),
  "Maquillador profesional": require("../../assets/icons/maquilladora.png"),
  Manicurista: require("../../assets/icons/manicurista.png"),
  "Técnico en refrigeración": require("../../assets/icons/refrigeracion.png"),
  "Montador de muebles": require("../../assets/icons/montador_muebles.png"),
  Bartender: require("../../assets/icons/bartender.png"),
  "Mozos para eventos": require("../../assets/icons/mozo_eventos.png"),
  "Dj para eventos": require("../../assets/icons/dj_eventos.png"),
  "Instalador de cámaras": require("../../assets/icons/instalador_camaras.png"),
  "Animador infantil": require("../../assets/icons/animador_infantil.png"),
  "Profesor de yoga": require("../../assets/icons/profesor_yoga.png"),
  "Instructor de manejo": require("../../assets/icons/instructor_manejo.png"),
  "Lavado de autos": require("../../assets/icons/lavador_autos.png"),
  "guarderia de mascotas": require("../../assets/icons/guarderia_mascotas.png"),
  "Personal de seguridad": require("../../assets/icons/personal_seguridad.png"),
  "Coach financiero": require("../../assets/icons/coach_financiero.png"),
  "Redactor de contenidos": require("../../assets/icons/redactor_contenidos.png"),
  "Consultor de negocios": require("../../assets/icons/consultor_negocios.png"),
  "Instalador de paneles solares": require("../../assets/icons/instalador_paneles_solares.png"),
  "Reparador de electrodomésticos": require("../../assets/icons/reparador_electrodomesticos.png"),
  Tapicero: require("../../assets/icons/tapicero.png"),
  Modista: require("../../assets/icons/modista.png"),
  Sastre: require("../../assets/icons/sastre.png"),
  "Montador de estructuras": require("../../assets/icons/montador_estructuras.png"),
  "Diseñador industrial": require("../../assets/icons/disenador_industrial.png"),
  "Fotógrafo de producto": require("../../assets/icons/fotografo_productos.png"),
  "Traductor jurado": require("../../assets/icons/traductor_jurado.png"),
  "Desarrollador de apps": require("../../assets/icons/desarrollador_app.png"),
  "Gestor de ecommerce": require("../../assets/icons/gestor_ecommerce.png"),
  Abogado: require("../../assets/icons/abogado.png"),
  Artesano: require("../../assets/icons/artesano.png"),
  "Consultor ambiental": require("../../assets/icons/consultor_ambiental.png"),
  "Encargado de depósito": require("../../assets/icons/encargado_deposito.png"),
  Camarero: require("../../assets/icons/camarero.png"),
  Panadero: require("../../assets/icons/panadero.png"),
  Pastelero: require("../../assets/icons/pastelero.png"),
  Delivery: require("../../assets/icons/delivery.png"),
  "Personal de limpieza de oficinas": require("../../assets/icons/personal_limpieza_oficinas.png"),

  Ingeniero: require("../../assets/icons/ingeniero.png"),
  Médico: require("../../assets/icons/medico.png"),
  Arquitecto: require("../../assets/icons/arquitecto.png"),
  Odontólogo: require("../../assets/icons/odontologo.png"),
  "Salón de fiestas infantiles": require("../../assets/icons/salon_fiestas_infantiles.png"),
  "Salón de fiestas": require("../../assets/icons/salon_fiestas.png"),
  "Decoraciones para eventos": require("../../assets/icons/decoraciones_eventos.png"),
  "Instalador de aire acondicionado": require("../../assets/icons/aire_acondicionado.png"),
  "Gestor de trámites": require("../../assets/icons/gestor_tramites.png"),
  "Peluquería de mascotas": require("../../assets/icons/peluqueria_mascotas.png"),
  Cocinero: require("../../assets/icons/cocinero.png"),
  "Ayudante de cocina": require("../../assets/icons/ayudante_cocina.png"),
  "Empleada doméstica": require("../../assets/icons/empleada_domestica.png"),
  "Limpieza comercial": require("../../assets/icons/limpieza_comercial.png"),
};

export const categoriasPorSeccion = {
  Hogar: [
    "Electricista",
    "Gasista",
    "Plomero",
    "Pintor",
    "Carpintero",
    "Cerrajero",
    "Jardinero",
    "Albañil",
    "Tapicero",
    "Reparaciones en el hogar",
    "Servicio de limpieza",
    "Montador de muebles",
    "Montador de estructuras",
    "Decorador de interiores",
    "Instalador de aire acondicionado",
    "Empleada doméstica",
  ],
  Transporte: [
    "Fletes",
    "Mudanzas",
    "Chofer privado",
    "Delivery",
    "Instructor de manejo",
    "Lavado de autos",
  ],
  Tecnología: [
    "Programador",
    "Técnico de PC",
    "Tester QA",
    "Desarrollador web",
    "Desarrollador de apps",
    "Instalador de cámaras",
    "Community Manager",
    "Editor de video",
    "Diseñador UX/UI",
    "Redactor de contenidos",
    "Gestor de ecommerce",
  ],
  Educación: [
    "Profesor particular",
    "Traductor",
    "Profesor de música",
    "Profesor de yoga",
  ],
  Profesionales: [
    "Contador",
    "Asistente contable",
    "Diseñador gráfico",
    "Consultor de negocios",
    "Abogado",
    "Consultor ambiental",
    "Marketing",
    "Gestor de redes",
    "Traductor jurado",
    "Atención al cliente",
    "Asistente virtual",
    "Coach financiero",
    "Coach de vida",
    "Ingeniero",
    "Arquitecto",
    "Médico",
    "Odontólogo",
    "Gestor de trámites",
  ],
  Mascotas: ["Paseador de perros", "Veterinario", "guarderia de mascotas" , "Peluquería de mascotas"],
  Bienestar: [
    "Entrenador personal",
    "Masajista",
    "Estilista",
    "Maquillador profesional",
    "Tatuador",
    "Manicurista",
    "Terapista ocupacional",
  ],
  Eventos: [
    "Organizador de eventos",
    "Fotógrafo",
    "Fotógrafo de producto",
    "Camarógrafo",
    "Animador infantil",
    "Mozos para eventos",
    "Bartender",
    "Dj para eventos",
    "Salón de fiestas infantiles",
    "Salón de fiestas",
    "Decoraciones para eventos",
  ],
  Cuidados: ["Cuidado de niños", "Cuidado de adultos mayores", "Enfermero"],
  Salud: ["Psicólogo", "Kinesiólogo", "Nutricionista"],
  Construcción: [
    "Soldador",
    "Herrero",
    "Instalador de paneles solares",
    "Reparador de electrodomésticos",
  ],
  "Arte Y Cultura": [
    "Ilustrador",
    "Guionista",
    "Diseñador industrial",
    "Sastre",
    "Modista",
    "Artesano",
  ],
  "Oficios Generales": [
    "Encargado de depósito",
    "Camarero",
    "Panadero",
    "Pastelero",
    "Personal de limpieza de oficinas",
    "Personal de seguridad",
    "Cocinero",
    "Ayudante de cocina",
    "Limpieza comercial",
  ],
};
